//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPhieuXuatHang
    {
        public int MaPhieuXuat { get; set; }
        public int MaHangHoa { get; set; }
        public Nullable<int> SoLuongXuat { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
        public virtual PhieuXuatHang PhieuXuatHang { get; set; }
    }
}
