//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLDaiLyEntities : DbContext
    {
        public QLDaiLyEntities()
            : base("name=QLDaiLyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTPhieuXuatHang> CTPhieuXuatHangs { get; set; }
        public virtual DbSet<DaiLy> DaiLies { get; set; }
        public virtual DbSet<DonViTinh> DonViTinhs { get; set; }
        public virtual DbSet<HangHoa> HangHoas { get; set; }
        public virtual DbSet<LoaiDaiLy> LoaiDaiLies { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<PhieuThuTien> PhieuThuTiens { get; set; }
        public virtual DbSet<PhieuXuatHang> PhieuXuatHangs { get; set; }
        public virtual DbSet<Quan> Quans { get; set; }
    
        public virtual ObjectResult<sp_DanhSachDaiLy_Result> sp_DanhSachDaiLy()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DanhSachDaiLy_Result>("sp_DanhSachDaiLy");
        }
    
        public virtual ObjectResult<sp_DanhSachDaiLy1_Result> sp_DanhSachDaiLy1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DanhSachDaiLy1_Result>("sp_DanhSachDaiLy1");
        }
    }
}
