using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;

namespace QLDaiLy
{
    public partial class frmCTPhieuXuatHang : DevExpress.XtraEditors.XtraForm
    {
        DAL.QLDaiLyEntities db = new DAL.QLDaiLyEntities();


        public frmCTPhieuXuatHang()
        {
            InitializeComponent();
        }

        
        private void FormLoad()
        {
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            DAL.QLDaiLyEntities dbContext = new DAL.QLDaiLyEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            int maphieuxuat = int.Parse(lbMaPhieuXuat.Text);
            dbContext.CTPhieuXuatHangs.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                //cTPhieuXuatHangsBindingSource.DataSource = dbContext.CTPhieuXuatHangs.Local.ToBindingList();
                
                cTPhieuXuatHangsBindingSource.DataSource = dbContext.CTPhieuXuatHangs.Where(p => p.MaPhieuXuat == maphieuxuat).ToList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());


            // Prevent the focused cell from being highlighted.
            gridViewHangHoa.OptionsSelection.EnableAppearanceFocusedCell = false;
            // Draw a dotted focus rectangle around the entire row.
            gridViewHangHoa.FocusRectStyle = DevExpress.XtraGrid.Views.Grid.DrawFocusRectStyle.RowFocus;


            //  Tính số lượng hàng hóa
            int TongSoHangHoa = db.CTPhieuXuatHangs.Where(p => p.MaPhieuXuat == maphieuxuat).Count();
            //int TongSoHangHoa = gridViewHangHoa.DataRowCount;
            lbTongHangHoa.Text = TongSoHangHoa.ToString();
        }


        private void frmCTPhieuXuatHang_Load(object sender, EventArgs e)
        {
            this.FormLoad();
        }


        private void btnDong_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}