using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;
using BUS;

namespace QLDaiLy
{
    public partial class frmDVTNgungKinhDoanh : DevExpress.XtraEditors.XtraForm
    {
        public event EventHandler XuLySuDungLaiDVT;

        private void KhiSuDungLaiDVT(EventArgs e)
        {
            var handler = XuLySuDungLaiDVT;
            if (handler != null)
            {
                handler(this, e);
            }
        }


        DAL.QLDaiLyEntities db = new DAL.QLDaiLyEntities();


        public frmDVTNgungKinhDoanh()
        {
            InitializeComponent();
        }


        private void FormLoad()
        {
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            DAL.QLDaiLyEntities dbContext = new DAL.QLDaiLyEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.DonViTinhs.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                //donViTinhsBindingSource.DataSource = dbContext.DonViTinhs.Local.ToBindingList();
                donViTinhsBindingSource.DataSource = dbContext.DonViTinhs.Where(d => d.TinhTrang == 0).ToList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());


            // Prevent the focused cell from being highlighted.
            gridViewDVTNgungSD.OptionsSelection.EnableAppearanceFocusedCell = false;
            // Draw a dotted focus rectangle around the entire row.
            gridViewDVTNgungSD.FocusRectStyle = DevExpress.XtraGrid.Views.Grid.DrawFocusRectStyle.RowFocus;
        }


        private void frmDVTNgungKinhDoanh_Load(object sender, EventArgs e)
        {
            this.FormLoad();
        }


        private void btnTaiSuDung_ButtonClick(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {
            int madvt = int.Parse(gridViewDVTNgungSD.GetFocusedRowCellValue("MaDVT").ToString());
            string tendvt = gridViewDVTNgungSD.GetFocusedRowCellValue("TenDVT").ToString();

            var tb = MessageBox.Show(string.Format("Bạn có chắc chắn muốn tái sử dụng đơn vị tính <{0}> ?", tendvt), "Thông báo", MessageBoxButtons.YesNo, MessageBoxIcon.Warning);
            if (tb == DialogResult.Yes)
            {
                BUS_DonViTinh dvt = new BUS_DonViTinh();
                var flag = dvt.TaiSuDungDonViTinh(madvt);
                if (flag == true)
                {
                    MessageBox.Show(string.Format("Bạn đã tiếp tục sử dụng đơn vị tính <{0}> thành công.", tendvt), "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    this.FormLoad();
                    KhiSuDungLaiDVT(EventArgs.Empty);   //  https://msdn.microsoft.com/en-us/library/9aackb16(v=vs.110).aspx
                }
            }
            else
            {
                return;
            }
        }


        private void txtTuKhoa_TextChanged(object sender, EventArgs e)
        {
            var tukhoa = txtTuKhoa.Text;
            var query = db.DonViTinhs
                          .Where(d => d.TenDVT.ToLower().Contains(tukhoa.ToLower()) && d.TinhTrang == 0)
                          .ToList();

            donViTinhsBindingSource.DataSource = query;

            if (string.IsNullOrEmpty(txtTuKhoa.Text))
            {
                donViTinhsBindingSource.DataSource = db.DonViTinhs.Where(d => d.TinhTrang == 0).ToList();
            }
        }
    }
}