using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;

namespace QLDaiLy
{
    public partial class frmDSNV : DevExpress.XtraEditors.XtraForm
    {
        public frmDSNV()
        {
            InitializeComponent();
        }


        private void FormLoad()
        {
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            DAL.QLDaiLyEntities dbContext = new DAL.QLDaiLyEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.NguoiDungs.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                //nguoiDungsBindingSource.DataSource = dbContext.NguoiDungs.Local.ToBindingList();

                nguoiDungsBindingSource.DataSource = dbContext.NguoiDungs.Where(nd => nd.TinhTrang == 1 && nd.Loai == 0).ToList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());


            // Make the grid read-only.
            gridViewNhanVien.OptionsBehavior.Editable = false;
            // Prevent the focused cell from being highlighted.
            gridViewNhanVien.OptionsSelection.EnableAppearanceFocusedCell = false;
            // Draw a dotted focus rectangle around the entire row.
            gridViewNhanVien.FocusRectStyle = DevExpress.XtraGrid.Views.Grid.DrawFocusRectStyle.RowFocus;
        }


        private void frmDSNV_Load(object sender, EventArgs e)
        {
            this.FormLoad();
        }
    }
}