using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using BUS;
using DevExpress.XtraEditors.Controls;
using System.Data.Entity;
using DevExpress.XtraGrid.Views.Grid;
using System.Globalization;
using System.Collections;

namespace QLDaiLy
{
    public partial class frmLapPhieuXuatHang : DevExpress.XtraEditors.XtraForm
    {
        DAL.QLDaiLyEntities db = new DAL.QLDaiLyEntities();

        DataTable dt = new DataTable();


        public event EventHandler XuLyThemPhieuXuat;

        private void KhiThemPhieuXuat(EventArgs e)
        {
            var handler = XuLyThemPhieuXuat;
            if (handler != null)
            {
                handler(this, e);
            }
        }


        public frmLapPhieuXuatHang()
        {
            InitializeComponent();
        }


        private void FormLoad()
        {
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            DAL.QLDaiLyEntities dbContext = new DAL.QLDaiLyEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.HangHoas.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                //hangHoasBindingSource1.DataSource = dbContext.HangHoas.Local.ToBindingList();

                hangHoasBindingSource1.DataSource = dbContext.HangHoas.Where(h => h.TinhTrang == 1).ToList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());


            // Prevent the focused cell from being highlighted.
            gridViewHangHoa.OptionsSelection.EnableAppearanceFocusedCell = false;
            gridViewGioHang.OptionsSelection.EnableAppearanceFocusedCell = false;
            // Draw a dotted focus rectangle around the entire row.
            gridViewHangHoa.FocusRectStyle = DevExpress.XtraGrid.Views.Grid.DrawFocusRectStyle.RowFocus;
            gridViewGioHang.FocusRectStyle = DevExpress.XtraGrid.Views.Grid.DrawFocusRectStyle.RowFocus;
        }


        private void frmLapPhieuXuatHang_Load(object sender, EventArgs e)
        {
            this.FormLoad();


            //  https://www.devexpress.com/Support/Center/Question/Details/Q20064/comboboxedit-how-do-you-set-the-datasource

            //  Lookup-edit Đại lý
            BUS_DaiLy dl = new BUS_DaiLy();
            cbDaiLy.Properties.DataSource = dl.DanhSachDaiLy();

            cbDaiLy.Properties.DisplayMember = "TenDaiLy";
            cbDaiLy.Properties.ValueMember = "MaDaiLy";
            cbDaiLy.Properties.Columns.Add(new LookUpColumnInfo("TenDaiLy", "Tên Đại Lý"));
            cbDaiLy.Properties.Columns.Add(new LookUpColumnInfo("Quan", "Quận"));
            cbDaiLy.Properties.Columns.Add(new LookUpColumnInfo("DiaChi", "Địa Chỉ"));

            //  Date edit
            dtpNgayLap.EditValue = DateTime.Now;


            //  Thêm hàng hóa vào giỏ hàng
            dt = new DataTable();
            dt.Columns.Add("Mã Hàng Hóa");
            dt.Columns.Add("Tên Hàng Hóa");
            dt.Columns.Add("Đơn Vị Tính");
            dt.Columns.Add("Đơn Giá");
            dt.Columns.Add("Số Lượng Mua");
            dt.Columns.Add("Thành Tiền");

            dgvGioHang.DataSource = dt;
        }


        private bool KiemTraDuLieu()
        {
            ErrorChecker.Clear();  //  giả sử ban đầu mọi dữ liệu là đúng

            if (cbDaiLy.EditValue == null)
            {
                ErrorChecker.BlinkRate = 500;
                ErrorChecker.SetError(cbDaiLy, "Không được để trống.");
                return false;
            }
            else
            {
                ErrorChecker.Clear();
            }

            return true;
        }


        //  Thêm hàng hóa vào giỏ hàng
        private void btnMua_ButtonClick(object sender, ButtonPressedEventArgs e)
        {
            //  https://www.youtube.com/watch?v=2139TgNMD6s

            DataRow dr = dt.NewRow();

            // mã hàng hóa đang chọn mua
            int mahh = int.Parse(gridViewHangHoa.GetFocusedRowCellValue("MaHangHoa").ToString());

            if (gridViewGioHang.DataRowCount == 0) // giỏ hàng đang trống
            {
                //  Thêm hàng hóa vào giỏ hàng
                dr[0] = gridViewHangHoa.GetFocusedRowCellValue("MaHangHoa").ToString();
                dr[1] = gridViewHangHoa.GetFocusedRowCellValue("TenHangHoa").ToString();
                dr[2] = gridViewHangHoa.GetFocusedRowCellValue("DonViTinh.TenDVT").ToString();
                dr[3] = gridViewHangHoa.GetFocusedRowCellValue("DonGia").ToString();
                dr[4] = 0;
                dr[5] = int.Parse(dr[3].ToString()) * int.Parse(dr[4].ToString());

                dt.Rows.Add(dr);
                dgvGioHang.DataSource = dt;


                gridViewGioHang.Columns[0].Visible = false;
                //  https://documentation.devexpress.com/WindowsForms/DevExpress.XtraGrid.Columns.GridColumn.ReadOnly.property
                gridViewGioHang.Columns[0].OptionsColumn.AllowEdit = false;
                gridViewGioHang.Columns[1].OptionsColumn.AllowEdit = false;
                gridViewGioHang.Columns[2].OptionsColumn.AllowEdit = false;
                gridViewGioHang.Columns[3].OptionsColumn.AllowEdit = false;
                gridViewGioHang.Columns[5].OptionsColumn.AllowEdit = false;

                gridViewGioHang.Columns[0].OptionsColumn.ReadOnly = true; 
                gridViewGioHang.Columns[1].OptionsColumn.ReadOnly = true;
                gridViewGioHang.Columns[2].OptionsColumn.ReadOnly = true;
                gridViewGioHang.Columns[3].OptionsColumn.ReadOnly = true;
                gridViewGioHang.Columns[5].OptionsColumn.ReadOnly = true;

                gridViewGioHang.Columns[1].AppearanceCell.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
                gridViewGioHang.Columns[1].AppearanceCell.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;
                gridViewGioHang.Columns[2].AppearanceCell.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
                gridViewGioHang.Columns[2].AppearanceCell.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;
                gridViewGioHang.Columns[3].AppearanceCell.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
                gridViewGioHang.Columns[3].AppearanceCell.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;
                gridViewGioHang.Columns[4].AppearanceCell.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
                gridViewGioHang.Columns[4].AppearanceCell.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;
                gridViewGioHang.Columns[5].AppearanceCell.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
                gridViewGioHang.Columns[5].AppearanceCell.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;

                gridViewGioHang.Columns[1].AppearanceHeader.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold);
                gridViewGioHang.Columns[1].AppearanceHeader.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
                gridViewGioHang.Columns[1].AppearanceHeader.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;
                gridViewGioHang.Columns[2].AppearanceHeader.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold);
                gridViewGioHang.Columns[2].AppearanceHeader.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
                gridViewGioHang.Columns[2].AppearanceHeader.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;
                gridViewGioHang.Columns[3].AppearanceHeader.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold);
                gridViewGioHang.Columns[3].AppearanceHeader.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
                gridViewGioHang.Columns[3].AppearanceHeader.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;
                gridViewGioHang.Columns[4].AppearanceHeader.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold);
                gridViewGioHang.Columns[4].AppearanceHeader.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
                gridViewGioHang.Columns[4].AppearanceHeader.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;
                gridViewGioHang.Columns[5].AppearanceHeader.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold);
                gridViewGioHang.Columns[5].AppearanceHeader.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
                gridViewGioHang.Columns[5].AppearanceHeader.TextOptions.VAlignment = DevExpress.Utils.VertAlignment.Center;
            }
            else
            {
                int flag = 1;
                for (int i = 0; i < gridViewGioHang.DataRowCount; i++)
                {
                    // mã hàng hóa đang có trong giỏ hàng
                    int mahh_giohang = int.Parse(gridViewGioHang.GetRowCellValue(i, gridViewGioHang.Columns[0]).ToString());

                    if (mahh == mahh_giohang)  //  trùng mã hàng hóa => hàng hóa đã có trong giỏ hàng
                    {
                        flag = 0;
                        break;
                    }
                }

                if (flag == 1)
                {
                    //  Thêm hàng hóa vào giỏ hàng
                    dr[0] = gridViewHangHoa.GetFocusedRowCellValue("MaHangHoa").ToString();
                    dr[1] = gridViewHangHoa.GetFocusedRowCellValue("TenHangHoa").ToString();
                    dr[2] = gridViewHangHoa.GetFocusedRowCellValue("DonViTinh.TenDVT").ToString();
                    dr[3] = gridViewHangHoa.GetFocusedRowCellValue("DonGia").ToString();
                    dr[4] = 0;
                    dr[5] = int.Parse(dr[3].ToString()) * int.Parse(dr[4].ToString());

                    dt.Rows.Add(dr);
                    dgvGioHang.DataSource = dt;
                }
                else
                {
                    string tenhh = gridViewHangHoa.GetFocusedRowCellValue("TenHangHoa").ToString();
                    MessageBox.Show(string.Format("<{0}> đã có trong giỏ hàng.", tenhh), "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
        }


        private int TinhTongTien()
        {
            for (int i = 0; i < gridViewGioHang.DataRowCount; i++)
            {
                DataRow row = gridViewGioHang.GetDataRow(i);

                int dongia = int.Parse(row[3].ToString());
                int slmua = int.Parse(row[4].ToString());
                int thanhtien = dongia * slmua;

                gridViewGioHang.SetRowCellValue(i, gridViewGioHang.Columns[5], string.Format("{0:N0}", thanhtien));
            }
            
            int tongtien = 0;
            for (int i = 0; i < gridViewGioHang.DataRowCount; i++)
            {
                DataRow row = gridViewGioHang.GetDataRow(i);

                //  https://stackoverflow.com/questions/4094334/how-to-format-a-currency-string-to-integer
                int thanhtien = int.Parse(row[5].ToString(), NumberStyles.Currency);
                tongtien = tongtien + thanhtien;
            }

            return tongtien;
        }


        private void gridViewGioHang_CellValueChanged(object sender, DevExpress.XtraGrid.Views.Base.CellValueChangedEventArgs e)
        {
            lbTongTien.Text = "0";
        }


        private bool SoLuongMuaHopLe()
        {
            for (int i = 0; i < gridViewGioHang.DataRowCount; i++)
            {
                string slmua = gridViewGioHang.GetRowCellValue(i, gridViewGioHang.Columns[4]).ToString();

                //  https://stackoverflow.com/questions/19715303/regex-that-accepts-only-numbers-0-9-and-no-characters
                if (!System.Text.RegularExpressions.Regex.IsMatch(slmua, "^[0-9]*$") || string.IsNullOrEmpty(slmua) || int.Parse(slmua) < 0)
                {
                    return false;
                }
            }
            return true;
        }


        private void btnTinhTongTien_Click(object sender, EventArgs e)
        {
            if (gridViewGioHang.DataRowCount == 0)
            {
                MessageBox.Show("Giỏ hàng rỗng.", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }
            else
            {
                if (SoLuongMuaHopLe())
                {
                    // kiểm tra đã nhập số lượng mua hay chưa
                    int flag = 1;
                    int flag_slton = 1;  // kiểm tra nếu số lượng mua lớn hơn tồn kho
                    int soluongton;
                    ArrayList tenhh = new ArrayList();

                    for (int i = 0; i < gridViewGioHang.DataRowCount; i++)
                    {
                        DataRow row = gridViewGioHang.GetDataRow(i);

                        int slmua = int.Parse(row[4].ToString());

                        int mahh_giohang = int.Parse(row[0].ToString());

                        if (slmua == 0)
                        {
                            flag = 0;
                            break;
                        }


                        // kiểm tra nếu số lượng mua lớn hơn tồn kho
                        for (int j = 0; j < gridViewHangHoa.DataRowCount; j++)
                        {
                            int mahh = int.Parse(gridViewHangHoa.GetRowCellValue(j, gridViewHangHoa.Columns["MaHangHoa"]).ToString());

                            if (mahh_giohang == mahh)
                            {
                                soluongton = int.Parse(gridViewHangHoa.GetRowCellValue(j, gridViewHangHoa.Columns["SoLuong"]).ToString());

                                if (slmua > soluongton)
                                {
                                    flag_slton = 0;
                                    tenhh.Add(row[1].ToString());  // lấy tên hàng hóa
                                    break;
                                }
                            }
                        }
                    }
                    
                    if (flag == 0)
                    {
                        MessageBox.Show("Chưa nhập số lượng mua.", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                    if (flag_slton == 0)
                    {
                        foreach (string ten in tenhh)
                        {
                            MessageBox.Show(string.Format("Hàng hóa:\n{0}\n\nSố lượng mua lớn hơn tồn kho!\nBạn hãy kiểm tra lại.", ten), "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        }
                    }
                    if (flag == 1 && flag_slton == 1)
                    {
                        int tongtien = TinhTongTien();
                        lbTongTien.Text = string.Format("{0:N0}", tongtien);
                    }
                }
                else
                {
                    MessageBox.Show("Số lượng mua không hợp lệ.", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
        }


        private void txtTuKhoa_TextChanged(object sender, EventArgs e)
        {
            var tukhoa = txtTuKhoa.Text;
            var query = db.HangHoas
                          .Where(hh => hh.TenHangHoa.ToLower().Contains(tukhoa.ToLower()) && hh.TinhTrang == 1)
                          .ToList();

            dgvHangHoa.DataSource = query;

            if (string.IsNullOrEmpty(txtTuKhoa.Text))
            {
                dgvHangHoa.DataSource = db.HangHoas.Where(hh => hh.TinhTrang == 1).ToList();
            }
        }


        private void btnXoaGioHang_Click(object sender, EventArgs e)
        {
            if (gridViewGioHang.DataRowCount == 0)
            {
                MessageBox.Show("Giỏ hàng rỗng.", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
            else
            {
                var tb = MessageBox.Show("Bạn có chắc chắn muốn xóa tất cả hàng hóa khỏi giỏ hàng ?", "Thông báo", MessageBoxButtons.YesNo, MessageBoxIcon.Warning);
                if (tb == DialogResult.Yes)
                {
                    gridViewGioHang.OptionsSelection.MultiSelect = true;
                    gridViewGioHang.SelectAll();
                    gridViewGioHang.DeleteSelectedRows();
                    lbTongTien.Text = "0";
                    gridViewGioHang.OptionsSelection.MultiSelect = false;
                    MessageBox.Show("Bạn đã xóa giỏ hàng thành công.", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
                else
                {
                    return;
                }
            }
        }


        private void btnXoaHangHoa_Click(object sender, EventArgs e)
        {
            if (gridViewGioHang.DataRowCount == 0)
            {
                MessageBox.Show("Giỏ hàng rỗng.", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
            else
            {
                string tenhh = gridViewGioHang.GetFocusedRowCellValue(gridViewGioHang.Columns[1]).ToString();

                var tb = MessageBox.Show(string.Format("Bạn có chắc chắn muốn xóa <{0}> khỏi giỏ hàng ?", tenhh), "Thông báo", MessageBoxButtons.YesNo, MessageBoxIcon.Warning);
                if (tb == DialogResult.Yes)
                {
                    gridViewGioHang.DeleteSelectedRows();
                    int tongtien = TinhTongTien();
                    lbTongTien.Text = string.Format("{0:N0}", tongtien);
                    MessageBox.Show(string.Format("Bạn đã xóa <{0}> khỏi giỏ hàng thành công.", tenhh), "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
                else
                {
                    return;
                }
            }
        }


        private void btnThem_Click(object sender, EventArgs e)
        {
            if (KiemTraDuLieu())
            {
                if (string.IsNullOrEmpty(lbTongTien.Text) || gridViewGioHang.DataRowCount == 0)
                {
                    MessageBox.Show("Giỏ hàng rỗng.", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    return;
                }
                if (double.Parse(lbTongTien.Text) == 0)
                {
                    MessageBox.Show("Chưa tính tổng tiền.", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    return;
                }
                else
                {
                    BUS_PhieuXuatHang pxh = new BUS_PhieuXuatHang();

                    int madaily = int.Parse(cbDaiLy.EditValue.ToString());
                    int manhanvien = BUS_NguoiDung.CurUser.MaNguoiDung;
                    DateTime ngayxuat = DateTime.Parse(dtpNgayLap.EditValue.ToString());
                    double tongtien = double.Parse(lbTongTien.Text, NumberStyles.Currency);

                    int maphieuxuat = pxh.PhieuXuatHang(madaily, manhanvien, ngayxuat, tongtien);

                    if (maphieuxuat != 0 && maphieuxuat != -1)
                    {
                        for (int i = 0; i < gridViewGioHang.DataRowCount; i++)
                        {
                            DataRow row = gridViewGioHang.GetDataRow(i);

                            int mahh = int.Parse(row[0].ToString());
                            int soluongxuat = int.Parse(row[4].ToString());
                            double dongia = double.Parse(row[3].ToString());
                            double thanhtien = double.Parse(row[5].ToString());

                            pxh.CTPhieuXuatHang(maphieuxuat, mahh, soluongxuat, dongia, thanhtien);
                        }

                        KhiThemPhieuXuat(EventArgs.Empty);   //  https://msdn.microsoft.com/en-us/library/9aackb16(v=vs.110).aspx

                        MessageBox.Show("Bạn đã lập phiếu xuất hàng thành công.", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);

                        this.FormLoad();  //  cập nhật số lượng hàng hóa tồn kho
                    }
                    if (maphieuxuat == 0)
                    {
                        MessageBox.Show("Lập phiếu xuất hàng thất bại.\nBạn nên kiểm tra lại dữ liệu hoặc liên hệ Admin.", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                    if (maphieuxuat == -1)
                    {
                        MessageBox.Show("Lập phiếu xuất hàng thất bại.\nTiền nợ đã vượt quá tiền nợ tối đa.\nBạn phải thanh toán tiền nợ trước.", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                }
            }
        }
    }
}