using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;

namespace QLDaiLy
{
    public partial class frmXuatHang : DevExpress.XtraEditors.XtraForm
    {
        public frmXuatHang()
        {
            InitializeComponent();
        }


        private void FormLoad()
        {
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            DAL.QLDaiLyEntities dbContext = new DAL.QLDaiLyEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.PhieuXuatHangs.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                phieuXuatHangsBindingSource.DataSource = dbContext.PhieuXuatHangs.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());

            
            // Prevent the focused cell from being highlighted.
            gridViewPhieuXuatHang.OptionsSelection.EnableAppearanceFocusedCell = false;
            // Draw a dotted focus rectangle around the entire row.
            gridViewPhieuXuatHang.FocusRectStyle = DevExpress.XtraGrid.Views.Grid.DrawFocusRectStyle.RowFocus;
        }


        private void frmXuatHang_Load(object sender, EventArgs e)
        {
            this.FormLoad();
        }


        private void navbarThem_LinkClicked(object sender, DevExpress.XtraNavBar.NavBarLinkEventArgs e)
        {
            frmLapPhieuXuatHang frm = new frmLapPhieuXuatHang();
            frm.XuLyThemPhieuXuat += frmXuatHang_Load;
            frm.ShowDialog();
        }


        private void btnChiTiet_ButtonClick(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {
            frmCTPhieuXuatHang frm = new frmCTPhieuXuatHang();
            frm.ShowDialog();
        }
    }
}